DROP TABLE IF EXISTS `MARLBORO`;
CREATE TABLE `MARLBORO (
  `ROW_NAME_KEY` VARCHAR(250),
  `MarlboroId` VARCHAR(512),
  `MarlboroPassWd` VARCHAR(512),
  `MarlboroContent` VARCHAR(512),
  PRIMARY KEY (`ROW_NAME_KEY`)
);
DROP TABLE IF EXISTS `TESTDATA`;
CREATE TABLE 'TESTDATA' (
	`ROW_NAME_KEY` VARCHAR(250),
	`MarlboroId` VARCHAR(512),
	`MarlboroPw` VARCHAR(512),
	`MarlboroNumber` VARCHAR(512),
	PRIMARY KEY (`ROW_NAME_KEY`)
);

